#!/bin/bash

# STARTUP
xsetroot -cursor_name left_ptr
sxhkd &
polybar top &

if [[ $(xrandr -q | grep 'HDMI2 connected') ]]; then
  xrandr --output eDP1 --primary  1920x1080 --rotate normal --output HDMI2 --mode 1920x1080 --rotate normal --above eDP1
fi 

# MONITORS
bspc monitor eDP1  -d 1 2 3
bspc monitor HDMI2 -d 4 5 6 

bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true

bspc config border_width           2
bspc config window_gap             5

bspc config split_ratio            0.66
bspc config click_to_focus         true
bspc config focus_follows_pointer  false
bspc config pointer_modifier       mod1

bspc config automatic_scheme       longest_side

bspc rule -a Firefox desktop='^2'
bspc rule -a NVIM desktop = '^1'
